### ISSUE TITLE
bug: links not show if main mac/nodeid has lsb set (impair)

### ISSUE THREAD

**Issue by Adorfer** [plumpudding/hopglass#2]
Wenn die NodeID eines Knoten ungerade ist, dann werden für diesen Node keine graphen gezeigt. 
Es tauchen auch keine Links in der Nodeinfo-Box auf. 

Dieses ist relevant, weil Vmware/ESXI per default auch (oder gar mit Vorliebe) ungerade MACs vergibt für die VM-interfaces. 

Hotfix: Sobald man im  /lib/gluon/core/sysconfig/primary_mac am betreffenen Node in der letzten Stelle einen geraden Wert einträgt sind die Links für den Hoplgass sichtbar. (Mit anderen worten: An /etc/config/network o.ä. muss man nicht dran, da können die ggf. vorhandenen ungeraden MACs bleiben.)

**Comment by plumpudding** [comment]
falsches projekt. bitte im server neu öffnen, ich kann nichts verschieben..
