### ISSUE TITLE
uci commands from coordinates picker

### ISSUE THREAD

**Issue by lrnzo** [plumpudding/hopglass#43]
if you pick coordinates, they appear on the left side of the screen. you switch between plain and uci view. this is a very nice feature but i think there should also be an

uci set gluon-node-info.@location[0].static_location='1'

and maybee even an

uci set gluon-node-info.@location[0].auto_location='0'

in case you want to set coordinates for a router which has autolocation until now.

**Comment by anoymouserver** [comment]
I haven't seen neither the `static_location` nor the `auto_location` flag anywhere until now.

How should the autolocation work and which router does support it at the moment?

**Comment by lrnzo** [comment]
here in the nordwest.freifunk.net community we have that option in our firmware. i don't know if there are other communities that do also have it. For details

git clone git@git.nordwest.freifunk.net:ffnw-firmware/packages.git

and take a look at libwlocate and ffnw-config-mode-geo-location.

**Comment by plumpudding** [comment]
We can't support special setups of single communities. Create a fork.
