### ISSUE TITLE
Balkenlänge der statistischen Daten

### ISSUE THREAD

**Issue by oszilloskop** [plumpudding/hopglass#45]
Bei den statistischen Daten bekommt die Balkenanzeige mehr Raum als die Balkenbezeichnung davor.
Ist die Balkenbezeichnung nun sehr lang (z.B. Router-Hardwaremodelle), so wird der Text abgeschnitten und es gehen wichtige Informationen verloren.

**Beispiel:**
![bildschirmfoto 2016-06-13 um 15 02 45](https://cloud.githubusercontent.com/assets/1434390/16008674/6638089e-3179-11e6-8ec3-fdc08e239526.png)

Wäre es möglich die Länge der Balken (besonders dem max. Balken, also dem dunkelblauen) etwas zu reduzieren? So, dass dem Text vor dem Balken mehr Platz gegeben würde?

**Beispiel:**
![bildschirmfoto 2016-06-13 um 15 01 54](https://cloud.githubusercontent.com/assets/1434390/16008719/8bf902d6-3179-11e6-9a4c-ff2c90dea296.png)

EDIT:
Ich benutze Chrome als Browser. Safari verhält es sich aber identisch.

**Comment by plumpudding** [comment]
Das Problem ist, dass die Aufteilung von Balken- und Textlänge für alle Statistiken gleich ist. Wenn man für die Hardwaremodelle die Aufteilung ändert, muss sie für alle geändert werden. Es wäre wünschenswert, die Aufteilung nur für die Hardwaremodelle zu ändern.

**Comment by plumpudding** [comment]
Behoben. Thx @mar-v-in
