### ISSUE TITLE
add "search" for hostname 

### ISSUE THREAD

**Issue by sap-dev** [plumpudding/hopglass#52]
hey,

it would be very nice, at the top of the hopglass frontend there is an input to search for Router.
Can you implemented ist?

**Comment by plumpudding** [comment]
I usually just use ctrl+f in the node list to find the node. A search field above the node list would be a great extra.

**Comment by sap-dev** [comment]
Yes, tge searchbox can sgow you all router in the list. Can you implemend this nice Feature?

**Comment by Moorviper** [comment]
this is one of the features i actually want to port from mesh viewer to hopglass

on my list actually is search via hostname and count clients in a mesh

**Comment by plumpudding** [comment]
not every e has nodeinfo afaik

**Comment by sap-dev** [comment]
Any news here? It is a very nice feature

**Comment by Moorviper** [comment]
i and mostly sheogorath XD finished to port clientspermesh to hopeless commit comes tomorrow because i am too trunk ;-)

on this function there was the same problem which causes the filter didn't work

**Comment by Moorviper** [comment]
so here it is:
https://github.com/plumpudding/hopglass/pull/63
