### ISSUE TITLE
Typo "Durchsatz Gesammt" 

### ISSUE THREAD

**Issue by mfuhrmann** [plumpudding/hopglass#64]
Should be "Gesamt".
Found on node page (second graph). eg. https://meshviewer.fulda.freifunk.net/#!v:m;n:a42bb0d957b8

![image](https://cloud.githubusercontent.com/assets/4995222/18474711/be9b3a3c-79c3-11e6-9a17-d5a2ec396b17.png)

**Comment by plumpudding** [comment]
This is not a hopglass issue.

**Comment by Moorviper** [comment]
typo in config.json i will fix it ;-)
