### ISSUE TITLE
Typo "Laufzeit und wahl des Gateways"

### ISSUE THREAD

**Issue by mfuhrmann** [plumpudding/hopglass#65]
Should be "Laufzeit und Wahl des Gateways".

Found on node page, fourth graph. eg. https://meshviewer.fulda.freifunk.net/#!v:m;n:a42bb0d957b8

![image](https://cloud.githubusercontent.com/assets/4995222/18474765/f5388b12-79c3-11e6-8bf0-1fd79584d30a.png)

**Comment by plumpudding** [comment]
This is not a hopglass issue either
