### ISSUE TITLE
more understandable marking for semi-offline nodes

### ISSUE THREAD

**Issue by sap-dev** [plumpudding/hopglass#66]
Hi,

wir haben aktuell das Problem, dass bei uns immer mehr Router unter verschwundene Router auftauchenen, nach wie vor grün sind und Die letzten Nachrichten vor Stunden ankamen.

Beispiel: http://srv11.ffnw.de/hood-os/#!v:m;n:14cc20ba7220

Wie kommt es dazu?

Jemand ne Ahnung?

**Comment by plumpudding** [comment]
Wenn der Server keine Pakete von Router erhält, aber ein b benachbarter Router bahauptet, ihn als Nachbar zu haben...

**Comment by sap-dev** [comment]
Okay, welche Gründe könnte es denn haben, das er keine Daten mehr sendet? Surfen kann ich, sprich der Tunnel ist da..

**Comment by plumpudding** [comment]
Ich sage es mal so: Pinge mal deine Knoten vom Mapserver aus. Wahrscheinlich hast du zweistelligen Packet loss.
