### ISSUE TITLE
maximized window in android not minimizable

### ISSUE THREAD

**Issue by rubo77** [plumpudding/hopglass#69]
If you use pinch to zoom to enlarge the page on android in chrome, by starting the pinch bolow the map in the white area of the page, it can happen, that you maximize so far, that you ony see the map without anything else. from then on, another pinch will only work inside the map, but not for the page any more, so there is no way to get the page smaller again, to see the nodes info below.

you can only close the tab and start a new tab to load the site from the start

**Comment by plumpudding** [comment]
I can't reproduce that. What version of chrome are you using?

**Comment by rubo77** [comment]
on android 4.4 chrome 52.0

I guess its on all versions

- it is quite easy, scroll down, so you see the info below the map.
- zoom so it is all very large fonts
- scroll back up to the map, so the map fills the whole window

**Comment by plumpudding** [comment]
With Chrome 56 on Android 6.0.1 I can't reproduce that. Please try updating your browser.

**Comment by rubo77** [comment]
updated and it is the same

**Comment by rubo77** [comment]
can you pinch to zoom the page in chrome 56? so that the font is really large?

**Comment by plumpudding** [comment]
I don't know what you did wrong but this is not a HopGlass issue. You are not supposed to scroll in the card area.

**Comment by rubo77** [comment]
It is not an urgent issue, but it exists.

I am not talking about the card area (map area).  
Below the map there is white background with text on it. the statistics and node names and so on.

there you can pinch to zoom to enlarge the page.

then you swipe back up to the map and you are stuck. Because if the map fills the screen, you can only swipe inside the map, but you cannot swipe the page any more.

It often happens, so I have to close the tab. the same on other pages where you have some google maps or such, that "steal" the zoom functionality.

I tested it on another android 7 with the same chrome and there it is not possible to zoom. but that handy has a 6'' screen. mine only 5'' so maybe the prohibition to zoom does not work on smaller screens?
