### ISSUE TITLE
Gateway mapping not using the complete mac for lookup

### ISSUE THREAD

**Issue by ecsv** [plumpudding/hopglass#77]
I've just noticed that only 8 characters of the 17 characters from the gateway and gateway_nexthop mac address are used for the lookup of the node information. This resulted in complete mismappings (e.g. to complete different cities as nexthop). This happens because multiple device macs start with the same 8 characters.

* wrong: https://vpn01.freifunk-vogtland.net/hopglass-broken/#!v:m;n:68725168a285
* correct: https://vpn01.freifunk-vogtland.net/hopglass/#!v:m;n:68725168a285

The "correct" version was made using the modification from https://github.com/FreifunkVogtland/hopglass/commit/a5e0f5fdc063ebc0052f988520a0f8b1ccf4b802

The broken version is 7e6d054e980b2f2d0798cb449bc9c62abef7b8fd (+ patch https://github.com/FreifunkVogtland/hopglass/commit/04953a7ebff406ca86a9a08402eb3c28a752a240 to show the uplink info)

This could also be caused by not yet switching to hopglass-server (which may use a 8 byte identifier instead of the complete mac address).

**Comment by plumpudding** [comment]
It should be much cleaner in the current master due to some commits by @mar-v-in

**Comment by ecsv** [comment]
Now it is not working at all in my setup. But at least the "var n = nodeDict[d.substr(0, 8)]" is now gone in the hopglass source code with commit ccc5f0f5267fe6caf366abff61660a2587ac9e97
